### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by p3yot3** [goldcoin/goldcoin#10]
When compiling from source on Ubuntu 14.04 64bit using:

make -f makefile.unix

I get the following error:

/bin/sh ../share/genbuild.sh obj/build.h
../share/genbuild.sh: 33: ../share/genbuild.sh: cannot create obj/build.h: Directory nonexistent
../share/genbuild.sh: 34: ../share/genbuild.sh: cannot create obj/build.h: Directory nonexistent
make: *** [obj/build.h] Error 2

I've compiled many wallets on this setup so am sure all dependecies are met. I'm able to build the goldcoinrebase version without issue, but end up with litecoin execs instead of goldcoin. The precompiled linux binary won't run, complaining of:

error while loading shared libraries: libboost_system.so.1.55.0: cannot open shared object file: No such file or directory

**Comment by microguy** [comment]
The Goldcoin daemon makes use of the QDateTime Class in the QT library for localized date conversion, thus it requires libqt in order to build. This unique dependency is used in for 51% attack defense system.

**Comment by p3yot3** [comment]
Ah, OK. There's no mention of that in the build notes that I can see.  What is the recommended QT version to install?

Regards.

**Comment by psionin** [comment]
Hi, please check out this guide for building it on Linux: [https://www.gldtalk.org/index.php?topic=1209.0](https://www.gldtalk.org/index.php?topic=1209.0)

The first error should be resolved by just doing a `mkdir obj` before running `make`, and the other one by `sudo apt-get install libboost-all-dev`?

**Comment by p3yot3** [comment]
Hi psionin,

Just to be sure, I should create the obj directory in the src folder - is that correct?

I already have libboost-all-dev installed.

regards.

**Comment by p3yot3** [comment]
Success!

Adding the obj folder to the src directory solved the problem - thank you psionin for the suggestion.

There seems to be a massive amount of bloat in the repo, 1.2Gb for a coin wallet is huge. Hopefully dev will make the required changes by adding the missing obj folder to the repo & clean it up a little, as it took me nearly 3 days to figure out the compile problems.

Regards.

**Comment by akumaburn** [comment]
The "barerepo" branch contains only the source code and none of the dependencies and is much smaller. The master branch contains everything  you need to build goldcoin from src and a bunch of extras.

I realize this is confusing, we may change the barerepo branch to master and the master branch to dev in the future.
