### ISSUE TITLE
Segwit leftovers require removal

### ISSUE THREAD

**Issue by akumaburn** [goldcoin/goldcoin#2]
#### What files need to be fixed? (Please list them all)
miner.h, mining.cpp, validation.cpp, validation.h

#### What needs to be done?
Remove some segwit left-overs

#### Why?
To meet end-goal
#

**Comment by Stouse49** [comment]
First commit f9d5c2cca92413df1d9f26b5e6317f0da970f58d is only the first part of necessary changes to remove all of the remaining SegWit code.

I will await feedback on removing WITNESS_SCALE_FACTOR and GetTransactionWeight() from many more files.  Additionally SERIALIZE_TRANSACTION_NO_WITNESS can be removed.

**Comment by akumaburn** [comment]
I think its pretty much been nixed from the codebase at this point.

**Comment by Stouse49** [comment]
There are still some parts left.

**Comment by Stouse49** [comment]
I reopened this because there are still a few parts of Segwit remaining.  Several things were found this week.

**Comment by Stouse49** [comment]
Everything is removed except for a few unused parameter warnings.  This will be addressed in another issue: #27.
