### ISSUE TITLE
Setup TestNet Parameters

### ISSUE THREAD

**Issue by Stouse49** [goldcoin/goldcoin#5]
### Describe the issue
Update to Litecoin 0.14.2 leaves TestNet broken

### Is this a bug in the codebase(not a usage issue) that needs to be fixed?
Yes.

#### What files need to be fixed? (Please list them all)
chainparams.cpp

#### What needs to be done?
Add TestNet parameters from GoldCoin 0.6 codebase.  Ports, seeds, checkpoints, hashes.

Currently it appears that the Genesis block of testnet is the same as mainnet.
https://github.com/goldcoin/goldcoin/blob/master/src/main.cpp#L2721

After starting the current GoldCoin client with -testnet, we find that the genesis block hash is the same as mainnet.

#### Why?
To get the testnet working again, we will need 0.6 and 0.14.2 nodes using the same blockchain.

**Comment by Stouse49** [comment]
Option 1 - Use the current blockchain and start the testnet from a specific height on one 0.6 node.  Then have the other nodes connected to it and sync.

Option 2 - Create a new TestNet genesis block, change 0.6 code for this and then start a node from 0.  This would require changing all the forks for the testnet to lower values to we can get the the GoldenRiver and 51% Defense forks earlier.

**Comment by akumaburn** [comment]
I think Option 1 is preferred initially here, as we do most of our testing in closed group fashion. For later purposes (after initial release) I think changing the testnet genesis would be a good idea so we can have some rolling tests going on.

**Comment by Stouse49** [comment]
message start appears to be the same for mainnet and testnet.  probably not an issue since they use different ports.

**Comment by Stouse49** [comment]
```
//required include only for generating a genesis block
#include "arith_uint256.h"        

//in chainparams.cpp:
//        genesis = CreateGenesisBlock(1296688602, 4, 0x207fffff, 1, 50 * COIN);
//	  <the following code is inserted here>
//        consensus.hashGenesisBlock = genesis.GetHash();  

if (true) {
    genesis.nNonce = 0;

    // This will figure out a valid hash and Nonce if you're
    // creating a different genesis block:
    arith_uint256 hashTarget;
    hashTarget.SetCompact(0x207fffff);
    while (UintToArith256(genesis.GetPoWHash()) > hashTarget)
    {
        ++genesis.nNonce;
        if (genesis.nNonce == 0)
        {
            printf("NONCE WRAPPED, incrementing time");
            ++genesis.nTime;
        }
if (genesis.nNonce % 10000 == 0)
{
    printf("nonce %08u: hash = %s \n", genesis.nNonce, genesis.GetHash().ToString().c_str());
}
    }
}


LogPrintf("block.GetHash() == %s\n", genesis.GetHash().ToString().c_str());
LogPrintf("block.hashMerkleRoot == %s\n", genesis.hashMerkleRoot.ToString().c_str());
LogPrintf("block.nTime = %u \n", genesis.nTime);
LogPrintf("block.nNonce = %u \n", genesis.nNonce);
LogPrintf("block.nBits = %u \n", genesis.nBits);

//After running once, look at the debug.log file.  be above output will be at the top.
```

**Comment by Stouse49** [comment]
This code here will not allow minimum difficulty blocks on testnet if the block time is >  4 minutes unless the fork for Testnet is made before julyFork2.

```
		// Only change once per interval, or at protocol switch height
		// After julyFork2 we change difficulty at every block.. so we want this only to happen before that..
		if ((nHeight % nInterval != 0) &&
		        (nHeight != nDifficultySwitchHeight || fTestNet) && (nHeight <= julyFork2))
		{
			// Special difficulty rule for testnet:
			if (fTestNet)
			{
				// If the new block's timestamp is more than 2* 10 minutes
				// then allow mining of a min-difficulty block.
				if (pblock->nTime > pindexLast->nTime + nTargetSpacing * 2)
					return nProofOfWorkLimit;
				else
				{
					// Return the last non-special-min-difficulty-rules-block
					const CBlockIndex* pindex = pindexLast;
					while (pindex->pprev && pindex->nHeight % nInterval != 0 && pindex->nBits == nProofOfWorkLimit)
						pindex = pindex->pprev;
					return pindex->nBits;
				}
			}

			return pindexLast->nBits;
}
```

**Comment by Stouse49** [comment]
The problem with using option 1 is that the difficultly will be very high and it will take a while to get the difficulty to drop without modifying the old client.  In the bitcoin testnet, if a block takes longer than 20 minutes to be mined, then the difficulty (before that block is mined) is lowered to the minimum and mining can resume with out waiting to solve the block at the original difficulty.  The current Goldcoin DAA doesn't support that idea from what I can tell.

**Comment by Stouse49** [comment]
The testnet worked wonderfully and we found many issues that were solved.
